#!/data/data/com.termux/files/usr/bin/bash
# Mr.CodeHacker - Termux Installer
# Platform: Android (Termux)

BLUE='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;97m'
YELLOW='\033[0;33m'
RESET='\033[0m'

banner() {
    clear
    echo -e "${GREEN}"
    cat Banners/Banner3.txt 2>/dev/null || echo "===== MR.CODEHACKER ====="
    echo -e "${RESET}"
    echo -e "${WHITE}  OSINT TOOL - TERMUX INSTALLER${RESET}"
    echo -e "${WHITE}  ==============================${RESET}\n"
}

print_step() { echo -e "${BLUE}[*]${WHITE} $1${RESET}"; }
print_ok()   { echo -e "${GREEN}[+]${WHITE} $1${RESET}"; }
print_err()  { echo -e "${RED}[!]${WHITE} $1${RESET}"; }

install_packages() {
    print_step "Updating package lists..."
    pkg update -y && pkg upgrade -y

    print_step "Installing Python 3..."
    pkg install -y python

    print_step "Installing pip..."
    pkg install -y python-pip

    print_step "Installing whois..."
    pkg install -y whois

    print_step "Installing traceroute..."
    pkg install -y traceroute

    print_step "Installing PHP (for GUI)..."
    pkg install -y php

    print_step "Installing curl..."
    pkg install -y curl

    print_step "Installing Python requirements..."
    pip install --upgrade pip
    pip install -r requirements.txt

    print_ok "All packages installed successfully!"
}

write_config() {
    DIR="$(pwd)"
    print_step "Creating configuration file..."
    cat > Configuration/Configuration.ini << EOF
;THIS FILE HAS BEEN GENERATED BY MR.CODEHACKER INSTALLER
;CHANGE THESE VALUES TO UPDATE YOUR SETTINGS
;DO NOT CHANGE THE PARAMETER NAMES

[Smtp]
status = Disabled
email = None
password = None
destination = None
server = None
port = None

[Settings]
password = Holmes
api_key = None
proxy_list = Proxies/Proxy_list.txt
useragent_list = Useragents/Useragent.txt
show_logs = False
database = False
language = english
date_format = eu
path = $DIR
EOF
    rm -f Configuration/UNTILED.txt
    print_ok "Configuration file created!"
}

set_display() {
    echo "Mobile" > Display/Display.txt
    chmod +x Core/update.sh 2>/dev/null
    chmod +x Launchers/Launcher.sh 2>/dev/null
    print_ok "Display set to Mobile mode."
}

# ── MAIN ──────────────────────────────────────────────────────────────────────
banner
echo -e "${YELLOW}This will install Mr.CodeHacker and all required packages on Termux.${RESET}"
echo -e "${BLUE}[?]${WHITE} Do you want to continue? (1) YES  (2) NO${RESET}\n"
read -p "[#MR.CODEHACKER#]--> " confirm

if [ "$confirm" != "1" ]; then
    echo -e "\n${RED}[!]${WHITE} Installation cancelled.${RESET}\n"
    exit 1
fi

install_packages
write_config
set_display

echo -e "\n${GREEN}=============================="
echo -e "[+] INSTALLATION COMPLETE!"
echo -e "==============================${RESET}"
echo -e "${WHITE}Run the tool with:${RESET}"
echo -e "${GREEN}  python MrCodeHacker.py${RESET}\n"
