#!/bin/bash
# Mr.CodeHacker - macOS Installer
# Platform: macOS (requires Homebrew)

BLUE='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;97m'
YELLOW='\033[0;33m'
RESET='\033[0m'

banner() {
    clear
    echo -e "${GREEN}"
    cat Banners/Banner6.txt 2>/dev/null || echo "===== MR.CODEHACKER ====="
    echo -e "${RESET}"
    echo -e "${WHITE}  OSINT TOOL - macOS INSTALLER${RESET}"
    echo -e "${WHITE}  =============================\n${RESET}"
}

print_step() { echo -e "${BLUE}[*]${WHITE} $1${RESET}"; }
print_ok()   { echo -e "${GREEN}[+]${WHITE} $1${RESET}"; }
print_err()  { echo -e "${RED}[!]${WHITE} $1${RESET}"; }

check_brew() {
    if ! command -v brew &>/dev/null; then
        print_step "Homebrew not found. Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if ! command -v brew &>/dev/null; then
            print_err "Homebrew installation failed. Please install it manually: https://brew.sh"
            exit 1
        fi
        print_ok "Homebrew installed."
    else
        print_ok "Homebrew already installed."
    fi
}

check_python() {
    if ! command -v python3 &>/dev/null; then
        print_step "Installing Python 3..."
        brew install python3
    else
        print_ok "Python 3 already installed: $(python3 --version)"
    fi
}

install_packages() {
    check_brew

    print_step "Updating Homebrew..."
    brew update

    check_python

    print_step "Installing whois..."
    brew install whois

    print_step "Installing PHP (for GUI)..."
    brew install php

    print_step "Installing wkhtmltopdf (for PDF export)..."
    brew install --cask wkhtmltopdf 2>/dev/null || brew install wkhtmltopdf 2>/dev/null || \
        print_err "wkhtmltopdf skipped (install manually if needed for PDF features)"

    print_step "Creating virtual environment (.venv)..."
    python3 -m venv .venv

    print_step "Installing Python requirements inside venv..."
    .venv/bin/pip install --upgrade pip
    .venv/bin/pip install -r requirements.txt

    print_ok "All packages installed successfully!"
}

write_config() {
    DIR="$(pwd)"
    print_step "Creating configuration file..."
    cat > Configuration/Configuration.ini << EOF
;THIS FILE HAS BEEN GENERATED BY MR.CODEHACKER INSTALLER
;CHANGE THESE VALUES TO UPDATE YOUR SETTINGS
;DO NOT CHANGE THE PARAMETER NAMES

[Smtp]
status = Disabled
email = None
password = None
destination = None
server = None
port = None

[Settings]
password = Holmes
api_key = None
proxy_list = Proxies/Proxy_list.txt
useragent_list = Useragents/Useragent.txt
show_logs = False
database = False
language = english
date_format = eu
path = $DIR
EOF
    rm -f Configuration/UNTILED.txt
    print_ok "Configuration file created!"
}

set_display() {
    echo "Desktop" > Display/Display.txt
    chmod +x Core/update.sh 2>/dev/null
    chmod +x Launchers/Launcher.sh 2>/dev/null
    print_ok "Display set to Desktop mode."
}

# ── MAIN ──────────────────────────────────────────────────────────────────────
banner
echo -e "${YELLOW}This will install Mr.CodeHacker and all required packages on macOS.${RESET}"
echo -e "${BLUE}[?]${WHITE} Do you want to continue? (1) YES  (2) NO${RESET}\n"
read -p "[#MR.CODEHACKER#]--> " confirm

if [ "$confirm" != "1" ]; then
    echo -e "\n${RED}[!]${WHITE} Installation cancelled.${RESET}\n"
    exit 1
fi

install_packages
write_config
set_display

echo -e "\n${GREEN}=============================="
echo -e "[+] INSTALLATION COMPLETE!"
echo -e "==============================${RESET}"
echo -e "${WHITE}Run the tool with:${RESET}"
echo -e "${GREEN}  source .venv/bin/activate${RESET}"
echo -e "${GREEN}  python3 MrCodeHacker.py${RESET}\n"
