@ECHO OFF
TITLE Mr.CodeHacker Launcher
COLOR 0A

ECHO.
ECHO  ==========================================
ECHO   MR.CODEHACKER - AUTO LAUNCHER
ECHO  ==========================================
ECHO.

:: Change to script directory
CD /D "%~dp0"

:: Check Python
python --version >NUL 2>&1
IF ERRORLEVEL 1 (
    ECHO [!] Python not found. Installing via winget...
    winget install --id Python.Python.3 -e --silent --accept-source-agreements --accept-package-agreements
    :: Refresh PATH
    CALL RefreshEnv.cmd >NUL 2>&1
)

:: Create venv if missing
IF NOT EXIST ".venv\" (
    ECHO [*] Creating virtual environment...
    python -m venv .venv
    ECHO [*] Installing requirements...
    .venv\Scripts\pip install --upgrade pip --quiet
    .venv\Scripts\pip install -r requirements.txt --quiet
    ECHO [+] Requirements installed.
) ELSE (
    :: Check if pyqrcode is present
    .venv\Scripts\python -c "import pyqrcode" >NUL 2>&1
    IF ERRORLEVEL 1 (
        ECHO [*] Updating requirements...
        .venv\Scripts\pip install -r requirements.txt --quiet
    ) ELSE (
        ECHO [+] Virtual environment ready.
    )
)

:: Create config if missing
IF NOT EXIST "Configuration\Configuration.ini" (
    ECHO [*] Creating default configuration...
    (
        ECHO ;THIS FILE HAS BEEN GENERATED BY MR.CODEHACKER INSTALLER
        ECHO ;CHANGE THESE VALUES TO UPDATE YOUR SETTINGS
        ECHO ;DO NOT CHANGE THE PARAMETER NAMES
        ECHO.
        ECHO [Smtp]
        ECHO status = Disabled
        ECHO email = None
        ECHO password = None
        ECHO destination = None
        ECHO server = None
        ECHO port = None
        ECHO.
        ECHO [Settings]
        ECHO password = Holmes
        ECHO api_key = None
        ECHO proxy_list = Proxies/Proxy_list.txt
        ECHO useragent_list = Useragents/Useragent.txt
        ECHO show_logs = False
        ECHO database = False
        ECHO language = english
        ECHO date_format = eu
        ECHO path = %CD%
    ) > Configuration\Configuration.ini
    ECHO [+] Configuration created.
)

:: Set display mode
ECHO Desktop> Display\Display.txt

:: Launch tool
ECHO.
ECHO [+] Launching Mr.CodeHacker...
ECHO.
.venv\Scripts\python MrCodeHacker.py

PAUSE
