#!/bin/bash
# Mr.CodeHacker - Universal Auto Launcher
# Works on: macOS, Linux, Termux
# Usage: bash run.sh

BLUE='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;97m'
YELLOW='\033[0;33m'
RESET='\033[0m'

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

print_step() { echo -e "${BLUE}[*]${WHITE} $1${RESET}"; }
print_ok()   { echo -e "${GREEN}[+]${WHITE} $1${RESET}"; }
print_err()  { echo -e "${RED}[!]${WHITE} $1${RESET}"; exit 1; }

# ── Detect platform ───────────────────────────────────────────────────────────
detect_platform() {
    if [[ -d "/data/data/com.termux" ]]; then
        PLATFORM="termux"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        PLATFORM="macos"
    else
        PLATFORM="linux"
    fi
    print_ok "Platform: $PLATFORM"
}

# ── Install system packages if needed ────────────────────────────────────────
install_system_deps() {
    if [[ "$PLATFORM" == "termux" ]]; then
        if ! command -v python3 &>/dev/null; then
            print_step "Installing Python (Termux)..."
            pkg install -y python python-pip
        fi
        if ! command -v php &>/dev/null; then
            print_step "Installing PHP (Termux)..."
            pkg install -y php
        fi

    elif [[ "$PLATFORM" == "macos" ]]; then
        if ! command -v brew &>/dev/null; then
            print_step "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        if ! command -v python3 &>/dev/null; then
            print_step "Installing Python3..."
            brew install python3
        fi
        if ! command -v php &>/dev/null; then
            print_step "Installing PHP..."
            brew install php
        fi

    elif [[ "$PLATFORM" == "linux" ]]; then
        if ! command -v python3 &>/dev/null; then
            print_step "Installing Python3..."
            if command -v apt-get &>/dev/null; then
                sudo apt-get install -y python3 python3-pip python3-venv
            elif command -v dnf &>/dev/null; then
                sudo dnf install -y python3 python3-pip
            elif command -v pacman &>/dev/null; then
                sudo pacman -S --noconfirm python python-pip
            fi
        fi
    fi
}

# ── Setup virtual environment ─────────────────────────────────────────────────
setup_venv() {
    if [[ "$PLATFORM" == "termux" ]]; then
        # Termux doesn't need venv — use pip directly
        if ! python3 -c "import pyqrcode" &>/dev/null; then
            print_step "Installing Python requirements..."
            pip install -r requirements.txt
            print_ok "Requirements installed."
        else
            print_ok "Python requirements already satisfied."
        fi
    else
        if [[ ! -d ".venv" ]]; then
            print_step "Creating virtual environment..."
            python3 -m venv .venv
            print_step "Installing Python requirements..."
            .venv/bin/pip install --upgrade pip --quiet
            .venv/bin/pip install -r requirements.txt --quiet
            print_ok "Requirements installed."
        else
            # Check if requirements are installed
            if ! .venv/bin/python -c "import pyqrcode" &>/dev/null; then
                print_step "Updating Python requirements..."
                .venv/bin/pip install -r requirements.txt --quiet
                print_ok "Requirements updated."
            else
                print_ok "Virtual environment ready."
            fi
        fi
    fi
}

# ── Generate config if missing ────────────────────────────────────────────────
setup_config() {
    if [[ ! -f "Configuration/Configuration.ini" ]] || grep -q "UNTILED" "Configuration/Configuration.ini" 2>/dev/null; then
        print_step "Creating default configuration..."
        cat > Configuration/Configuration.ini << CONF
;THIS FILE HAS BEEN GENERATED BY MR.CODEHACKER INSTALLER
;CHANGE THESE VALUES TO UPDATE YOUR SETTINGS
;DO NOT CHANGE THE PARAMETER NAMES

[Smtp]
status = Disabled
email = None
password = None
destination = None
server = None
port = None

[Settings]
password = Holmes
api_key = None
proxy_list = Proxies/Proxy_list.txt
useragent_list = Useragents/Useragent.txt
show_logs = False
database = False
language = english
date_format = eu
path = $DIR
CONF
        print_ok "Configuration file created."
    fi
}

# ── Set display mode ──────────────────────────────────────────────────────────
setup_display() {
    if [[ "$PLATFORM" == "termux" ]]; then
        echo "Mobile" > Display/Display.txt
    else
        echo "Desktop" > Display/Display.txt
    fi
    chmod +x Core/update.sh 2>/dev/null
    chmod +x Launchers/Launcher.sh 2>/dev/null
}

# ── Run the tool ──────────────────────────────────────────────────────────────
run_tool() {
    echo ""
    print_ok "Launching Mr.CodeHacker..."
    echo ""
    if [[ "$PLATFORM" == "termux" ]]; then
        python3 MrCodeHacker.py
    else
        .venv/bin/python3 MrCodeHacker.py
    fi
}

# ── MAIN ──────────────────────────────────────────────────────────────────────
detect_platform
install_system_deps
setup_venv
setup_config
setup_display
run_tool
