# Mr.CodeHacker - Windows PowerShell Installer
# Platform: Windows 10 / 11
# Run via: Install.cmd (or right-click > Run with PowerShell)

$Host.UI.RawUI.WindowTitle = "Mr.CodeHacker Installer"

function Banner {
    Clear-Host
    try { Get-Content "Banners\Banner6.txt" } catch { Write-Host "===== MR.CODEHACKER =====" }
    Write-Host ""
    Write-Host "  OSINT TOOL - WINDOWS INSTALLER" -ForegroundColor Green
    Write-Host "  ================================`n" -ForegroundColor White
}

function PrintStep($msg) { Write-Host "[*] $msg" -ForegroundColor Cyan }
function PrintOk($msg)   { Write-Host "[+] $msg" -ForegroundColor Green }
function PrintErr($msg)  { Write-Host "[!] $msg" -ForegroundColor Red }

function Check-Admin {
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        PrintErr "Please run Install.cmd as Administrator (right-click > Run as administrator)."
        Read-Host "Press Enter to exit"
        exit 1
    }
}

function Check-Winget {
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        PrintErr "winget not found. Install 'App Installer' from the Microsoft Store, then re-run."
        Read-Host "Press Enter to exit"
        exit 1
    }
    PrintOk "winget is available."
}

function Install-Packages {
    PrintStep "Installing Python 3..."
    winget install --id Python.Python.3 -e --silent --accept-source-agreements --accept-package-agreements

    PrintStep "Installing PHP (via XAMPP)..."
    winget install --id ApacheFriends.Xampp.8.2 -e --silent --accept-source-agreements --accept-package-agreements

    # Refresh PATH so pip is usable in this session
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                [System.Environment]::GetEnvironmentVariable("Path", "User")

    PrintStep "Upgrading pip..."
    python -m pip install --upgrade pip

    PrintStep "Installing Python requirements..."
    python -m pip install -r requirements.txt

    PrintOk "All packages installed successfully!"
}

function Write-Config {
    $Dir = (Get-Location).Path
    PrintStep "Creating configuration file..."

    $config = @"
;THIS FILE HAS BEEN GENERATED BY MR.CODEHACKER INSTALLER
;CHANGE THESE VALUES TO UPDATE YOUR SETTINGS
;DO NOT CHANGE THE PARAMETER NAMES

[Smtp]
status = Disabled
email = None
password = None
destination = None
server = None
port = None

[Settings]
password = Holmes
api_key = None
proxy_list = Proxies/Proxy_list.txt
useragent_list = Useragents/Useragent.txt
show_logs = False
database = False
language = english
date_format = eu
path = $Dir
"@

    $config | Out-File -FilePath "Configuration\Configuration.ini" -Encoding ASCII
    Remove-Item -Path "Configuration\UNTILED.txt" -ErrorAction SilentlyContinue
    PrintOk "Configuration file created!"
}

function Set-Display {
    "Desktop" | Out-File -FilePath "Display\Display.txt" -Encoding ASCII
    PrintOk "Display set to Desktop mode."
}

# ── MAIN ──────────────────────────────────────────────────────────────────────
Banner
Check-Admin
Check-Winget

Write-Host "This will install Mr.CodeHacker and all required packages on Windows." -ForegroundColor Yellow
$confirm = Read-Host "`n[?] Do you want to continue? (1) YES  (2) NO`n`n[#MR.CODEHACKER#]-->"

if ($confirm -ne "1") {
    PrintErr "Installation cancelled."
    Read-Host "Press Enter to exit"
    exit 1
}

Install-Packages
Write-Config
Set-Display

Write-Host "`n==============================" -ForegroundColor Green
Write-Host "[+] INSTALLATION COMPLETE!"    -ForegroundColor Green
Write-Host "==============================`n" -ForegroundColor Green
Write-Host "Run the tool with:" -ForegroundColor White
Write-Host "  python MrCodeHacker.py`n" -ForegroundColor Green
Read-Host "Press Enter to exit"
